
#include "gba.h"
#include <stdio.h> 
#include <stdlib.h>
#include "game.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum {
  START,
  PLAY,
  HELP1,
  HELP2,
  HELP3,
} GBAState;

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;


  // Load initial game state
  GBAState state = START;
  Frisk frisk;
  frisk.col = 3;
  frisk.row = 75;
  frisk.height = 6;
  frisk.length = 6;
  frisk.lastr = frisk.row;
  frisk.lastc = frisk.col;

  Board board;
  board.numSquares = 121;
  int lastState = -1;
  /*
  for (int i = 0; i < 121; i++) {
    board.squares[i].color = (colors[rand() % ncolors]);
  }
  */

  

  while (1) {
    currentButtons = BUTTONS;  // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case START:
        if (lastState != 0) {
          fillScreenDMA(BLACK);
          drawCenteredString(20,115,20,20,"Game of Papyrus",WHITE);
          drawCenteredString(40,96,50,50,"Press Enter to Play", WHITE);
          lastState = 0;
        }
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = PLAY;
        } 
        // state = ?
        break;
      case PLAY:
        if (lastState != 1) {
          fillScreenDMA(BLACK);
          drawRectDMA(20, 60, 121, 121, WHITE);
          frisk.col = 3;
          frisk.row = 75;
          frisk.height = 6;
          frisk.length = 6;
          frisk.lastr = frisk.row;
          frisk.lastc = frisk.col;
          drawRectDMA(frisk.row, frisk.col, frisk.length, frisk.height, WHITE);
          waitForVBlank();
          setBoard(board);
          drawCenteredString(4,5, 10,10, "? [Tab]", GREEN);
          //drawRectDMA(0, 54, (WIDTH - 54), 40, LIGHTBLUE); 
          //drawRectDMA(70, )
          lastState = 1;
        }
        
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          if (frisk.row >= 1) {
            frisk.lastc = frisk.col;
            frisk.lastr = frisk.row;
            frisk.row = frisk.row - 1;   
            drawRectDMA(frisk.lastr,frisk.lastc,frisk.length, frisk.height, BLACK);
            drawRectDMA(frisk.row, frisk.col, frisk.length, frisk.height, WHITE);
          }
        } else if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          if (frisk.col < 54) {
            frisk.lastc = frisk.col;
            frisk.lastr = frisk.row;
            frisk.col = frisk.col + 1;
            drawRectDMA(frisk.lastr,frisk.lastc,frisk.length, frisk.height, BLACK);
            drawRectDMA(frisk.row, frisk.col, frisk.length, frisk.height, WHITE);
          }
        } else if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if (frisk.row < 154) {
            frisk.lastr = frisk.row;
            frisk.lastc = frisk.col;
            frisk.row = frisk.row + 1;
            drawRectDMA(frisk.lastr,frisk.lastc,frisk.length, frisk.height, BLACK);
            drawRectDMA(frisk.row, frisk.col, frisk.length, frisk.height, WHITE);
          }
        } else if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          if (frisk.col >= 1) {
            frisk.lastc = frisk.col;
            frisk.lastr = frisk.row;
            frisk.col = frisk.col - 1;
            drawRectDMA(frisk.lastr,frisk.lastc,frisk.length, frisk.height, BLACK);
            drawRectDMA(frisk.row, frisk.col, frisk.length, frisk.height, WHITE);

          }
        }
        state = PLAY;
        //((3 <= frisk.row && frisk.row <= 7) && (3 <= frisk.col && frisk.col <= 7)
        if ((3 <= frisk.row && frisk.row <= 7) && (3 <= frisk.col && frisk.col <= 7)) {
          waitForVBlank();
          state = HELP1;
          //fillScreenDMA(WHITE);
        }
        
        //printf("Last row: %d, last col: %d \n curr row: %d, curr col: %d", frisk.lastr, frisk.lastc, frisk.row, frisk.col);
        
        
        
        
        //drawRectDMA(frisk.lastr,frisk.lastc,frisk.length, frisk.height, BLACK);
        
        

        // state = ?
        break;
      case HELP1:
        /*
        pink = magenta -> no effect
        green = green -> no effect
        red  = red -> solid wall
        yellow = yellow -> must go back to the last tile
        orange = orange -> protagonist flavor is orange 
        purple = purple -> force protagonist to next tile in direction they are facing
                -> also make protagonist flavor lemon
        blue = blue -> next to yellow tile, acts lile a yellow tile
            -> if flavor is orange, acts like yellow tile
            -> otherwise has no effect
        */
        if (lastState != 2) {
          fillScreenDMA(WHITE);
          drawCenteredString(10,118,20,20,"Rules:", BLACK);
          drawRectDMA(36, 50, 9, 9, RED);
          drawCenteredString(35,130,10,10,"Cannot pass ", BLACK);
          drawRectDMA(56, 50, 9, 9, ORANGE);
          drawCenteredString(55,135,10,10,"Flavor is orange ", BLACK);
          drawRectDMA(76, 50, 9, 9, YELLOW);
          drawCenteredString(75,130,10,10,"Go back to last tile", BLACK);
          drawRectDMA(96, 50, 9, 9, GREEN);
          drawCenteredString(95,130,10,10,"No effect", BLACK);
          drawRectDMA(116, 50, 9,9, MAGENTA);
          drawCenteredString(115,130,10,10,"No effect", BLACK);
          drawCenteredString(146, 120, 15,15, "Next Page -> Press Enter", RED);
          lastState = 2;
        }
        if ((KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons))) {
          waitForVBlank();
          state = HELP2;
        }

        // state = ?
        break;
      case HELP2:
        if (lastState != 3) {
          fillScreenDMA(WHITE);
          lastState = 3;
          drawRectDMA(26, 30, 9,9, PURPLE);
          drawCenteredString(25,125, 10,10,"Jump to next tile,", BLACK);
          drawCenteredString(45,125,5,5,"flavor is lemon", BLACK);
          drawRectDMA(61, 30, 9,9, BLUE);
          drawCenteredString(60,130,10,10,"If next to  , acts like ", BLACK);
          drawRectDMA(61, 132, 8, 8, YELLOW);
          drawRectDMA(61, 204, 8, 8, YELLOW);
          drawCenteredString(78,120,10,10,"If flavor is orange, acts like ", BLACK);
          drawRectDMA(78, 215, 10, 10, YELLOW);
          drawCenteredString(97,130,5,5,"Otherwise, no effect ", BLACK);
          drawCenteredString(146, 120, 15,15, "Next Page -> Press SELECT", RED);
        }
        if ((KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons))) {
          waitForVBlank();
          state = HELP3;
        }

        // state = ?
        break;
      case HELP3:
        if (lastState != 4) {
          lastState = 4;
          fillScreenDMA(WHITE);
          drawCenteredString(20, 123, 5, 5, "Move with WASD", BLACK);
          drawCenteredString(40, 120, 10, 10, "Roll over   for Help", BLACK);
          drawChar(40, 122, '?', GREEN);
          drawCenteredString(57, 117, 10, 10, "or press [Tab]", BLACK);
          drawCenteredString(75, 122, 10, 10, "Get to the other side! :)", BLACK);
        }
        if ((KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons))) {
          waitForVBlank();
          state = PLAY;
        }
    }

    previousButtons = currentButtons;  // Store the current state of the buttons
  }

 

  return 0;
}
